name: CI/CD Pipeline

on:
  push:
    tags:
      - "dev*"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set execute permission on gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Docker Login and Cleanup on Server
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_SERVER: ${{ secrets.SSH_SERVER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${SSH_USER}@${SSH_SERVER} "
            docker rmi -f ${DOCKER_USERNAME}/forrrest-auth:dev ${DOCKER_USERNAME}/forrrest-app-management:dev || true
          "

      - name: Build and Push Docker Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/forrrest-auth:dev -f forrrest-authservice/Dockerfile-auth forrrest-authservice
          docker build -t ${{ secrets.DOCKER_USERNAME }}/forrrest-app-management:dev -f forrrest-appmanagementservice/Dockerfile-app forrrest-appmanagementservice
          docker push ${{ secrets.DOCKER_USERNAME }}/forrrest-auth:dev
          docker push ${{ secrets.DOCKER_USERNAME }}/forrrest-app-management:dev

      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }} "
            cd /home/${{ secrets.SSH_USER }}/dev &&
            docker-compose -f docker-compose-dev.yml down --remove-orphans &&
            docker-compose -f docker-compose-dev.yml pull &&
            docker-compose -f docker-compose-dev.yml up -d --build
          "
